// import Container from '../Components/container'
// import { ReactCompareSlider, ReactCompareSliderImage } from 'react-compare-slider';
// import Link from 'next/link';
// import Head from 'next/head';

// import ServiceCss from "../../styles/services.module.css"

// // export async function getServerSideProps () {

// //     const res = await fetch("http://localhost:3000/api/servicesimage")
// //     const data = await res.json()

// //     return {
// //         props: {
// //             data
// //         }
// //     }
// // }


// const Services = ({ data }) => {

//     return(
//         <>
//             <Container>

//             <Head>   
//                 <title>Clipping Path Service</title>
//                 <meta name="description" content="Generated by create next app" />
//                 <meta name="viewport" content="width=device-width, initial-scale=1" />
//                 <link rel="icon" type="" href="/img/favicon.png" />
//                 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />     
//             </Head>

//                 <div id={ServiceCss.heading_section}>
//                     <div className="row">
//                         <div className="col-lg-6">
//                             <h1>Clipping Path Service You Can Trust</h1>
//                             <p>Wanna know if we are the photo editing company you are looking for ?</p>

//                             <h4 id={ServiceCss.get_trial}>Get a free trial now.</h4>

//                             <div id={ServiceCss.certificate_section}>
//                                 <div className="row">
//                                     <div className="col-lg-4">
//                                         <div className="row">
//                                             <div className="col-3">
//                                                 <img src="/img/certified-professionals-icon.png.webp" alt="" />
//                                             </div>
//                                             <div className="col-9">
//                                                 <h4>150+</h4>
//                                                 <p>Certified Professionals</p>
//                                             </div>
//                                         </div>
//                                     </div>
//                                     <div className="col-lg-4">
//                                         <div className="row">
//                                             <div className="col-3">
//                                                 <img src="/img/faster-delivery-icon.png" alt="" />
//                                             </div>
//                                             <div className="col-9">
//                                                 <h4>63%</h4>
//                                                 <p>Faster Delivery</p>
//                                             </div>
//                                         </div>
//                                     </div>
//                                     <div className="col-lg-4">
//                                         <div className="row">
//                                             <div className="col-3">
//                                                 <img src="/img/lower-cost-icon.png" alt="" />
//                                             </div>
//                                             <div className="col-9">
//                                                 <h4>40%</h4>
//                                                 <p>Lower Cost</p>
//                                             </div>
//                                         </div>
//                                     </div>
//                                 </div>
//                             </div>

//                             <Link href="" className='btn btn-lg mt-4' id={ServiceCss.get_start_btn}>Get Started <i class="fa-solid fa-arrow-right"></i></Link>
//                         </div>

//                         <div className="col-lg-6"></div>
//                     </div>

//                     <div id={ServiceCss.client_impress_section}>
//                         <div className="row my-5">
//                             <div className="col-lg-6 text-end">
//                                 <h3 id={ServiceCss.impress_customer}>Impress Your Customers With Perfect Clipping Path</h3>
//                             </div>
//                             <div className="col-lg-6">
//                                 <p>Sell more as you dazzle your customers with crisp and clean product photos with the help of our outsourcing photo editing services.</p>
//                             </div>
//                         </div>
//                     </div>
//                 </div>

//                 <div className={ServiceCss.professional_photo_section_one}>
//                     <div className="container">
//                         <div className="row">
//                             <div className="col-lg-6">
//                                 <img src="./img/image-background-removal-services.png" alt="" />
//                             </div>
//                             <div className="col-lg-6">
//                                 <h2 className="heading">Outsource Photoshop Services for Ecommerce</h2>
//                                 <p>Statistics say, 75% of online shoppers decide to buy after seeing the product photos. If it’s of good quality, your brand will-</p>
//                                 <ul>
//                                     <li><i className="fa-solid fa-check"></i>Make a good impression</li>
//                                     <li><i className="fa-solid fa-check"></i>Appeal to the viewers</li>
//                                     <li><i className="fa-solid fa-check"></i>Get increased visitors</li>
//                                     <li><i className="fa-solid fa-check"></i>Get improved Conversion rate</li>
//                                     <li><i className="fa-solid fa-check"></i>All in all, receive boost up sales.</li>
//                                 </ul>
//                                 <p>We work behind the scenes to make you stand out in the front. Outsourcing photoshop services from us will pay you off. With a team of 150 experts, we are offering photo editing services in a wide variety of sectors.</p>
//                             </div>
//                         </div>
//                     </div>
//                 </div>

//                 <div className={ServiceCss.professional_photo_section_two}>
                    
//                         <h2 className="text-center heading">Photoshop Editing Services We Provide</h2>
//                         <p className="text-center">Get professional photoshop services online from Adobe Photoshop experts at Clipping Path Studio. Outsource industry-standard photo editing service at a competitive price; keep your stress at bay!</p>

//                         <div className="two_sub_section_one">
//                             <div className="row py-4">
//                                 <div className="col-lg-6">
//                                     <img src="./img/image-background-removal-services.png" alt="" />
//                                 </div>
//                                 <div className="col-lg-6">
//                                     <h2 className="heading_two">Photoshop Clipping Path</h2>
//                                     <p>Clipping Path is used for so many causes in the ecommerce business. So, if you are a photographer or dealing with an e-commerce business, you must need a <Link href="">photoshop clipping path service.</Link> Clipping path lets us separate one particular part of an image. After separating that, other editing works can be done there. <br /><br /> </p>
                
//                                     <p>We create the finest clipping path here, which is all done manually. So, there is no chance of having any issue with the image. We offer –</p>
                
//                                     <ul>
//                                         <li><i className="fa-solid fa-check"></i>Make a good impression</li>
//                                         <li><i className="fa-solid fa-check"></i>Appeal to the viewers</li>
//                                         <li><i className="fa-solid fa-check"></i>Get increased visitors</li>
//                                     </ul>
                
//                                     <Link href="" className="btn btn-lg mt-4">Get Free Trial</Link>
//                             </div>
//                         </div>
//                         </div>
                        
//                         <div className="two_sub_section_two">
//                             <div className="row py-4">
//                                 <div className="col-lg-6">
//                                     <h2 className="heading_two">Photoshop Background removal</h2>
//                                     <p>Want to remove backgrounds from pictures? Removing backgrounds from the image looks simple, but it requires expert hands. Distracting or attention-grabbing backgrounds often shift the focus from the subject. <br /><br />
                
//                                         We offer you to remove background from each and every kind of image. Our <a href="">image background removal service</a> includes –</p>
                
//                                     <ul>
//                                         <li><i className="fa-solid fa-check"></i>Product background removal</li>
//                                         <li><i className="fa-solid fa-check"></i>Remove background from complex images</li>
//                                         <li><i className="fa-solid fa-check"></i>Remove any unwanted part from an image</li>
//                                     </ul>
                
//                                     <Link href="" className="btn-lg btn mt-4">Get Free Trial</Link>
//                                 </div>
//                                 <div className="col-lg-6">
//                                     <img src="./img/image-background-removal-services.png" alt="" />
//                                 </div>
//                             </div>
//                         </div>  
                        
//                         <div className="two_sub_section_three">
//                             <div className="row py-4">
//                                 <div className="col-lg-6">
//                                     <img src="./img/image-background-removal-services.png" alt="" />
//                                 </div>

//                                 <div className="col-lg-6">
//                                     <h2 className="heading_two">Photoshop Image Masking</h2>
//                                         <p>Image masking is a multi-functional service that we provide. Masking is used for so many other works. To correct a specific part of an image, to work on a certain part, or to do different editing on different parts of the image.<br /><br />
                
//                                         Masking is also used to merge one part of an image with another.  Check what we provide –</p>
                
//                                     <ul>
//                                         <li><i className="fa-solid fa-check"></i>Masking any area of an image</li>
//                                         <li><i className="fa-solid fa-check"></i>Image cut out</li>
//                                         <li><i className="fa-solid fa-check"></i>Complex hand-made masking</li>
//                                         <li><i className="fa-solid fa-check"></i>Photoshop hair masking</li>
//                                     </ul>
                
//                                     <Link href="" className="btn btn-lg mt-4">Get Free Trial</Link> 
//                                 </div>
//                             </div>
//                         </div> 

//                         <div className="two_sub_section_four">
//                             <div className="row py-4">
//                                 <div className="col-lg-6">
//                                     <h2 className="heading_two">Ecommerce Image Editing</h2>
//                                     <p>An online business requires a specific kind of <a href="">ecommerce image editing service.</a> For instance, there are certain image patterns for sites like Amazon, eBay, Walmart, or social media like Instagram. So you need to customize your images according to the required pattern. Also, image quality needs to be high and should fulfill some criteria so that the images receive the correct attention. <br /><br />
                
//                                         We help our clients to reach that goal by –</p>
                
//                                     <ul>
//                                         <li><i className="fa-solid fa-check"></i>Creating images with specific requirements</li>
//                                         <li><i className="fa-solid fa-check"></i>Resize images </li>
//                                         <li><i className="fa-solid fa-check"></i>Maintaining the quality of ecommerce sites</li>
//                                     </ul>
                
//                                     <Link href="" className="btn-lg btn mt-4">Get Free Trial</Link>
//                                 </div>
//                                 <div className="col-lg-6">
//                                     <img src="./img/image-background-removal-services.png" alt="" />
//                                 </div>
//                             </div>
//                         </div>

//                 </div>


//                 <div className={ServiceCss.professional_photo_section_three}>

//                     <div className="container">
//                         <h2 className="text-center heading py-5 mb-0">Have Any Questions?- Here Is The Answers     <img src="./img/Group-4754.png" alt="" />
//                         </h2>

//                         <div className="accordion" id="accordionExample">
//                             <div className="accordion-item my-4">
//                             <h2 className="accordion-header" id="headingOne">
//                                 <button className="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
//                                     <p className="mb-0 accordion_title">How fast are your photoshop editing services?</p>
//                                 </button>
//                             </h2>
//                             <div id="collapseOne" className="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
//                                 <div className="accordion-body">
//                                 <p>It depends on some other factors. For instance, how   many images you wanna get done, how complicated those images are and finally, how fast you need those images. We prioritize your time. So, if you have hurry, we’ll do it faster and we deliver as fast as 6 hours.
//                                     </p>
//                                 </div>
//                             </div>
//                             </div>

//                             <div className="accordion-item my-4">
//                             <h2 className="accordion-header" id="headingTwo">
//                                 <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
//                                     <p className="mb-0 accordion_title">Do you offer bulk order discounts?</p>
//                                 </button>
//                             </h2>
//                             <div id="collapseTwo" className="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
//                                 <div className="accordion-body">
//                                     <p>Yes, we do. The more images you’ll order, the higher the discount will be. You can count the amount in our website. Just give your information like, number of images, time and all, you’ll get to know about the discount.
//                                     </p>
//                                 </div>
//                             </div>
//                             </div>

//                             <div className="accordion-item my-4">
//                             <h2 className="accordion-header" id="headingThree">
//                                 <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
//                                     <p className="mb-0 accordion_title">Why should I choose CPS for Photoshop photo editing needs?</p>
//                                 </button>
//                             </h2>
//                             <div id="collapseThree" className="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
//                                 <div className="accordion-body">
//                                     <p>Because we provide professional-level images at the most affordable price and that even within a short period of time. Our experience and commitment to our work have improved our services over the years. We can say that we provide one of the best photoshop editing services.
//                                     </p>
//                                 </div>
//                             </div>
//                             </div>

//                             <div className="accordion-item my-4">
//                                 <h2 className="accordion-header" id="headingFour">
//                                 <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
//                                     <p className="mb-0 accordion_title">Which Photoshop is best for editing?</p>
//                                 </button>
//                                 </h2>
//                                 <div id="collapseFour" className="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
//                                 <div className="accordion-body">
//                                     <p>Adobe Photoshop is mostly used to edit photos. We continuously update our photoshop and always use the latest version of photoshop so that we don’t miss any feature. We have some other prominent software too.
//                                     </p>
//                                 </div>
//                                 </div>
//                             </div>

//                         </div>
//                     </div>
//                 </div>



    

//             </Container>
//         </>
//     )
// }

// export default Services